version: 2
updates:
- package-ecosystem: gomod
  directories:
  - '/'
  - '/tools'
  groups:
    kube:
      applies-to: version-updates
      patterns:
      - k8s.io/*
    onsi:
      applies-to: version-updates
      patterns:
      - github.com/onsi/*
  schedule:
    interval: daily
  labels:
  - kind/deps
  commit-message:
    prefix: fix
    include: scope
