version: 2
updates:
- package-ecosystem: gomod
  directory: /
  groups:
    kube:
      applies-to: version-updates
      patterns:
      - k8s.io/*
  schedule:
    interval: daily
  labels:
  - kind/deps
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: gomod
  directory: /tools
  groups:
    kube:
      applies-to: version-updates
      patterns:
      - k8s.io/*
  schedule:
    interval: daily
  labels:
  - kind/deps
  commit-message:
    prefix: fix
    include: scope
